name: 'Create Module Metadata'
description: 'Action to create metadata for a module'
author: 'Your name or organization here'
inputs:
  tagName:
    description: The tag that will used for the module version
    required: false
    default: v0.1.0
  distDir:
    description: The directory where the catalog should be output
    required: false
    default: ./output
  strict:
    description: Flag indicating that strict validation should be performed
    required: false
    default: "false"
  validate:
    description: Flag indicating that the module metadata should be validated
    required: false
    default: "true"
  publishBranch:
    description: The branch where the catalog should be published
    required: false
    default: gh-pages
  metadataFile:
    description: The file containing the module metadata
    required: false
    default: module.yaml
  repoSlug:
    description: The repository slug (e.g. owner/repo)
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
