name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - v1
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: action
        uses: ./
        with:
          tagName: v3.0.0
          distDir: ./output
          strict: true
          validate: true
          repoSlug: 'cloud-native-toolkit/terraform-ocp-login'
      - name: Print module
        run: |
          if [[ ! -f ./output/index.yaml ]]; then
            echo "Output file not found"
            exit 1
          fi
          if [[ ! -f ./output/README.md ]]; then
            echo "Output README not found"
            exit 1
          fi
          cat ./output/index.yaml
